### PR TITLE
Merged emory updates into gh-pages

### PR DESCRIPTION
**Pull request by madhun999**

### CODE REVIEW

**Comment by madhun999** [comment]
Merged emory style stuff into gh-pages

**Comment by Lou123** [comment]
Wow, you have gave me a great start in the styles pages.   I knew I had a
great partner, I just didn't see it at first.  I will be scoping it out in
depth tonight and try to add some styling to it today and tomorrow. I just
never did a pull request.  Any suggestions/tips or best way to do a pull to
add my stuff.  I want to make sure I am doing it right and not causing any
issues for us.

**Comment by Lou123** [comment]
Also, what text editor are you using?  Please advise.

**Comment by madhun999** [comment]
Actually, Microsoft Visual Studio 2013.  It's not really a text editor as such, but it does have one built into it.

**Pull request merged**
